python .\src\main.py  player-1 &
python .\src\main.py  player-2 &
python .\src\main.py  player-3 &
python .\src\main.py  player-4 &
python .\src\main.py  player-5 &
python .\src\main.py  player-6 &
python .\src\main.py  player-7 &
python .\src\main.py  player-8 &
python .\src\main.py  player-9 &
python .\src\main.py  player-10 &